### ISSUE TITLE
Running application

### ISSUE THREAD

**Issue by akastrin** [mstahv/bootiful-neo4j-with-vaadin#1]
Could somebody please show, how to compile, install, and run the application. I don't know where to start.

Thank you in advance,
Andrej

**Comment by mstahv** [comment]
The SNAPSHOT release used for vaadin4spring seems to be deleted, I'll upgrade this to Vaadin Spring soon.

**Comment by mstahv** [comment]
Ah, it seems I had done that already :-) In short:

git clone ...
mvn install
java -jar target/generated-spring-boot.jar
